# Generated by Django 4.2 on 2024-07-21 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='disconunt_until',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
