# Generated by Django 4.2 on 2024-07-12 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('score', models.IntegerField(default=3)),
                ('comment', models.TextField(max_length=300, null=True)),
            ],
        ),
    ]
