# Generated by Django 4.2 on 2024-07-12 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_comments_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='siganture',
            field=models.CharField(default='Firma', max_length=100),
        ),
    ]
