# Generated by Django 4.2 on 2024-07-21 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('telefono', models.CharField(blank=True, max_length=12, null=True)),
                ('celular', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('compania', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('notas', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
